name: pipeline-demo-project
channels:
  - conda-forge
  - opensourceeconomics
  - r
dependencies:
  - python=3.7
  - pip
  - conda-build
  - matplotlib
  - pipeline
  - rpy2
  - seaborn
  - pip:
    - stargazer
  - r-stargazer
  - r-tidyverse
